version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
    name: prompt-db
